### ISSUE TITLE
Verify on more other objects than tibbles

### ISSUE THREAD

**Issue by gregleleu** [ropensci/assertr#100]
It would be nice to be able to use `{assertr}` in workflows that aren't tibbles, such as lists (or `{tidygraph}` objects).

It fails for now because of eval_tidy. Maybe a way to do it would be to change how `data`  is passed to eval_tidy? (I don't know enough about rlang to propose a solution, sorry :( )

Reprex:
```
library(magrittr)
library(assertr)
library(purrr)

## Making a list of numbrer from 1 to 10
a <- 1:10 %>% as.list()

## A test to see if all numbers are greater than one (using purrr) -> returns TRUE
a %>% 
  map_lgl(., ~{.x > 0}) %>% all()

### It would be cool if that worked
a %>% 
  verify(map_lgl(., ~{.x > 0}) %>% all())
```

**Comment by tonyfischetti** [comment]
This would be cool but I stopped following the vagaries of the tidyverse shortly before rlang.
If you know have an idea on how to implement it, please send a pull request
