### ISSUE TITLE
assertr in CRAN 2.7 and assertr 2.6.9000

### ISSUE THREAD

**Issue by JauntyJJS** [ropensci/assertr#101]
Hi,

There seems to be some large difference between the assertr (v2.7) installed from CRAN and the one install from github (v2.6.9000).
For example the verify function, the 2.7 CRAN version have no description argument 
![image](https://user-images.githubusercontent.com/9066508/94629600-dfce1480-02f5-11eb-81b4-13ca8dc1a3d2.png)

but the 2.6.9000 version has more argument and flexibility
![image](https://user-images.githubusercontent.com/9066508/94629673-0f7d1c80-02f6-11eb-9335-49a941987c0a.png)

Could I clarify if the functions in 2.6.9000 are going to be incorporated or not used in future versions.
Kindly advise.

**Comment by krystian8207** [comment]
This is strongly related to #96. @tonyfischetti do you plan to release the current master in the nearest future?

**Comment by tonyfischetti** [comment]
Working on this as we speak

**Comment by tonyfischetti** [comment]
The missing piece was was the pull request #104 which fixed
3 failures and 103 warnings from the tip of master

I bumped the version number and submitted it to CRAN
Once accepted, I'll close this issue and commit the latest with the
version bump

Thank you for your patience!

**Comment by tonyfischetti** [comment]
assertr 2.8 just hit cran!
