### ISSUE TITLE
Compatibility with sf data frames

### ISSUE THREAD

**Issue by gregleleu** [ropensci/assertr#102]
For its geospatial data frames, the sf package tweaks the `select` verb to make sure the geometry column is not subsetted out. Hence, it makes `assert` fail as it tries to apply the predicate on the geometry column [here](https://github.com/ropensci/assertr/blob/e69e369ef0082beb441616056451c18b21f2db4f/R/assertions.R#L102)  

One way to fix it would be to check if the data.frame is an sj object and get rid of the geometry column if that's the case.
```
if(inherits(sub.frame, "sf")) sub.frame <- sf::st_drop_geometry(sub.frame)
```

There might be other functions in the package where this could be useful.
I don't know what the implications are of calling a function of the sf package on dependencies etc.

**Comment by tonyfischetti** [comment]
This seems worthwhile. If you'd like to submit a pull request, I'd be happy to review it and merge it
