### ISSUE TITLE
warning "the condition has length > 1 and only the first element will be used" 

### ISSUE THREAD

**Issue by gregleleu** [ropensci/assertr#103]
I get the warning in the title on assert calls.

It comes from this line `if(class(log.mat)=="logical")` [here](https://github.com/ropensci/assertr/blob/e69e369ef0082beb441616056451c18b21f2db4f/R/assertions.R#L110)

as the object actually multiple classes:
```
> class(log.mat)
[1] "matrix" "array" 
```

Not sure what the best solution is, as I'm not sure what cases this covers.

In any case, the calculations are still ok.

**Comment by tonyfischetti** [comment]
I think this is now fixed. Can you replicate this with assertr 2.8?
