### ISSUE TITLE
How do you extract defective rows using AssertR in R?

### ISSUE THREAD

**Issue by datakilimba** [ropensci/assertr#110]
Dear all,

I stumbled across assertR recently. My work involves alot of daily data collection from multiple (>50) sources, so assertR offers me an opportunity to automate data quality enforcement/error discovery. I have a question which is best split in 2.

1. Can/does assertR store defective rows for displaying eg on a Shiny datatable (on a dashboard)? 
2. Can assertR filter good data (based on assertions imposed) and continue with workflow using the "cleaned" data, while doing 1 (above), for a data manager to peruse erroneous rows at his/her earliest convenience?

The example below is a simple one which tries to assert the column y is always positive (y>0). I just want to know if there is a way the analysis pipeline can continue uninterrupted (minus the erroneous data) but store defective data somewhere for use in another workflow (Shiny app display via Data Tables)?

``` r
library(tidyverse)
library(assertr)
#> Warning: package 'assertr' was built under R version 4.0.5

test = tribble(
  ~x,~y,
  1,4,
  3,8,
  0,-2
)

test %>% 
  assert(within_bounds(0,100),y)
#> Column 'y' violates assertion 'within_bounds(0, 100)' 1 time
#>     verb redux_fn             predicate column index value
#> 1 assert       NA within_bounds(0, 100)      y     3    -2
#> Error: assertr stopped execution
```

<sup>Created on 2021-04-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tonyfischetti** [comment]
Hi Datakilimba!

So a few things.
a) For showing errors in a shiny app, you may want to
look at https://github.com/Appsilon/data.validator
which using assertr internally

b)The offending info and rows are stored internally
and accessible. You may want to look into
`help("success_and_error_functions")`
after you load assertr.
Here an example, (I switched to `data.frame` because I
don't have `tribble` and I switched the place of the 0
in column x to better illustrate the point.

```r
> test <- data.frame(x=c(1, 0, 3),
+                    y=c(4, 8, -2))
> test %>%
+   assert(within_bounds(0,100), y,
+          error_fun=error_df_return)  -> tmp
> # looking at the returned data.frame
> tmp
    verb redux_fn             predicate column index value
1 assert       NA within_bounds(0, 100)      y     3    -2
> # access the index/indices/rows of offending data
> tmp$index
[1] 3
>
> # using multiple and chaining
> test %>%
+   chain_start %>%
+   assert(within_bounds(0,100), y) %>%
+   assert(within_bounds(1, 100), x) %>%
+   chain_end(error_fun=error_df_return) -> tmp
>
> tmp
    verb redux_fn             predicate column index value
1 assert       NA within_bounds(0, 100)      y     3    -2
2 assert       NA within_bounds(1, 100)      x     2     0
>
> tmp$index
[1] 3 2
```

**Comment by datakilimba** [comment]
Thank you, this seems neat and tidy. I will give this a go and if a pull request is needed I will go ahead :-).
