### ISSUE TITLE
How to assertr dataframe with two or more columns?

### ISSUE THREAD

**Issue by AlvaroMCMC** [ropensci/assertr#111]
I would need something like this, where the offending row in the fourth one.
```
library(assertr)
library(tidyverse)

tibble(
  a = c("x", "y", "z", "z"),
  b = c(1 , 2, 10, 15)
) %>% 
  assert(
    a == "z" & b == 10
  )

```

**Comment by tonyfischetti** [comment]
Creo q no entiendo :(
En el ejemplo el unico row que _no_ es incorrecto es el tercero

De todos modos, en el caso que mas que uno column necesita una prueba, hay que usar
`verify` asi

```
data.frame(a = c("x", "y", "z", "z"),
           b = c(1 , 2, 10, 15)) %>%
  verify(a == "z" & b==10)
# verification [a == "z" & b == 10] failed! (3 failures)

#    verb redux_fn          predicate column index value
# 1 verify       NA a == "z" & b == 10     NA     1    NA
# 2 verify       NA a == "z" & b == 10     NA     2    NA
##3 verify       NA a == "z" & b == 10     NA     4    NA

Error: assertr stopped execution
```

Espero que eso te ayudara

**Comment by AlvaroMCMC** [comment]
gracias Tony, en realidad lo que busco es encontrar las filas en donde, siendo a == "z", b debe ser 10. En ese caso la cuarta fila es la que no cumple con el requisito. La primera y segunda no lo incumplen.

**Comment by tonyfischetti** [comment]
Ah, ahora veo.
Si entiendo correcto, ¿esta bien si cualquiera en la primera fila  es algo otro de "z", pero si es "z", _es necesario_ q la segunda fila ser 10?
En este caso...
```
data.frame(a = c("x", "y", "z", "z"),
           b = c(1 , 2, 10, 15)) %>%
  verify(ifelse(a=="z", b==10, TRUE))
# verification [ifelse(a == "z", b == 10, TRUE)] failed! (1 failure)

#     verb redux_fn                       predicate column index value
# 1 verify       NA ifelse(a == "z", b == 10, TRUE)     NA     4    NA

# Error: assertr stopped execution
```

En el codico encima, `ifelse` verifica que "si `a` es "z", debe ser 10 en `b`. pero si `a` no es "z", cualquiera puede ser en `b`"

(Tambien functionará con `tibble`s, por supuesto, pero no tengo tidyverse disponible ahora mismo)

**Comment by AlvaroMCMC** [comment]
entiendo, gracias, sí resuelve mi problema.

**Comment by tonyfischetti** [comment]
¡De nada! Cuidate
