### ISSUE TITLE
How to get a more informative assertion when using `verify`?

### ISSUE THREAD

**Issue by AlvaroMCMC** [ropensci/assertr#116]
```
meses <- c("A", "B", "C")

tibble::tibble(
  mes = c("A", "b", "C")
) %>% 
  assertr::verify(mes %in% meses)
```
message from `verify`. It's correct as it says the error's index but in the `value` column does not show the value of the `mes` column from the `tibble` so I have to look for the row.
```
    verb redux_fn      predicate column index value
1 verify       NA mes %in% meses     NA     2    NA
```

desired output
```
    verb redux_fn      predicate column index value
1 verify       NA mes %in% meses     NA     2    b
```

**Comment by tonyfischetti** [comment]
Unfortunately, because of the way `verify` works internally, this isn't possible.
Check out the section called "verify vs. assert" in https://cran.r-project.org/web/packages/assertr/vignettes/assertr.html

The assert function is better used to handle this case... try
```
tibble::tibble(
  mes = c("A", "b", "C")
) %>% 
  assertr::assert(in_set(meses), mes)
```
