### ISSUE TITLE
new example for vignette

### ISSUE THREAD

**Issue by momeara** [ropensci/assertr#23]
Hi what a nice package--

Perhaps you'd like to add to your vignette that it's easy to check that a data frame column contains a column

```
data.frame(a=c(1,2,3)) %>%
    verify("a" %>% exists) %>%    # ok
    verify("b" %>% exists)        # fails
```

**Comment by tonyfischetti** [comment]
That would be super useful. Because of the nested migrator pipes, do you have any idea what `exists` would look like?

**Comment by momeara** [comment]
Exists already exists! If you try it, you'll see it works with the current version of assertr : D

**Comment by tonyfischetti** [comment]
Just checked this. It will return TRUE is there's a variable named the same name as the column to be checked...
```{r}
mpgg <- "this"
mtcars %>%
  verify("mpgg" %>% exists) %>%
  head # passes
```
Which can be really dangerous.
So you have to do this instead
```{r}
mpgg <- "this"
mtcars %>%
  verify(exists("mpgg", where=.)) %>%
  head # fails
```
I think it might be worth writing a dedicated wrapper function (I'll do it!).
What do you think?

**Comment by momeara** [comment]
Nice catch, yes, in this case a wrapper would be helpful.

**Comment by tonyfischetti** [comment]
Because I don't have any other "predicates" that can't be used with `verify` and not the other verbs I don't think I'm gonna write the wrapper function, but I'm gonna put it in the vignette!

**Comment by tonyfischetti** [comment]
I decided to implement this after all! It's `has_all_names` :) Thanks for the suggestion!

It's in the README and vignette now, too

**Comment by momeara** [comment]
👍
