### ISSUE TITLE
`df %>% assertr::assert(assertr::not_na, var)` gives incorrect message

### ISSUE THREAD

**Issue by jjchern** [ropensci/assertr#34]
Thanks for the great package!

Here's an incorrect message I got when calling the `not_na()` function through namespace:

``` R
df = data_frame(var = c(1, NA))
df %>% assertr::assert(assertr::not_na, var)
#> Error: 
#> Vector 'var' violates assertion '::' 1 time (value [NA] at index 2)
```

If `assertr` is loaded beforehand, the message is fine:

``` R
library(assertr)
df %>% assert(not_na, var)
#> Error: 
#> Vector 'var' violates assertion 'not_na' 1 time (value [NA] at index 2)
```

Also, is it possible to have a short cut function such as `assertr::assert_not_na(df, var)`?

**Comment by jjchern** [comment]
Perhaps `assertr::assert_not_na(df, var)` is too long. 

How about `assertr::nona(df, var)`? 

Also Stata has a command `isid` that verifies if a variable, or a combination of several variables, is uniquely identified. Maybe `assertr` can have a similar function? Something like

```R
assertr::isid(df, var)
assertr::isid(df, var1, var2)
```

I'm happy to submit a PR if you think these are useful functions to have.

Of course `nona` and `isid` are not verbs, and they can be easily generated with `assertr` and `magrittr`'s functional sequences. I understand if you think `assertr` is not a right place for these special functions. I can also put them into a small separate package. Maybe as a place to include special functions:

```R
comfirmr::nona(df, var)
comfirmr::isid(df, var)
comfirmr::isdummy(df, var)
comfirmr::positive(df, var)
comfirmr::negative(df, var)
comfirmr::nonzero(df, var)
```

**Comment by tonyfischetti** [comment]
(a) thanks for the kind words about the package!
(b) `is_id` is on the radar! The project is about to be subsumed by [ROpenSci](http://ropensci.org) so there's a lot of great stuff coming
(c) yeah, `assertr` might not be the right place for these but they can totally exist in a different package! Before anyone works on that, we should wait to see how the collaboration with ROpenSci will change the way some of those functions are implemented; the API won't change, but there might be changes that will effect the most graceful way to write those convenience functions.
(d) I'm not sure about the namespace thing :( I'll look into it

**Comment by tonyfischetti** [comment]
Haha, so I hope this isn't too late but I fixed the namespace issue. And I'm writing the `is_id` (I think I'm going to use `is_unique` though) right now :)
