### ISSUE TITLE
Assertion about dates

### ISSUE THREAD

**Issue by TonyLadson** [ropensci/assertr#36]
This is a feature request - thank you for all your work on assertr so far.  

Could there be assertions about dates?  

I realise I can write a predicate function or convert to numeric.  Just wondering about some built in approach.

Here are a couple of approaches I've used

```
within_dateRange <- function(x, date_min, date_max) {
  x > date_min & x < date_max
}

assert(within_bounds(as.numeric(as.Date('2015-01-01')), as.numeric(as.Date('2015-02-01'))), Sample_date)
```

```
mutate(Sample_date_num = as.numeric(Sample_date)) %>% 
assert(within_bounds(as.numeric(as.Date('2015-01-01')), as.numeric(as.Date('2015-02-01'))), Sample_date_num)
```

**Comment by tonyfischetti** [comment]
Thanks for the kind words....

There's no built-in approach yet. If I add this functionality to assertr (and the only reason I wouldn't is if it makes more sense to put it in another package) I would do it like this...

let's say I got a file like this called `dates.csv`
```
item,the_date
a,2016-09-02
b,2016-09-03
c,2016-09-03
d,2016-09-04
e,2016-09-04
f,2016-09-28
g,2016-09-29
h,2016-09-28
```

And I want to make sure all the dates are between September 1st and 30th...

```
library(lubridate)   # for the ymd (year-month-day), %within%, and %--% interval builder functions

these <- readr::read_csv("./dates.csv")

within_dates <- function(start_date, end_date){
  interval <- lubridate::`%--%`(start_date, end_date)
  closure <- function(adate){
    return(lubridate::`%within%`(adate, interval))
  }
  return(closure)
}

these %>%
  assert(within_dates(mdy("09-01-16"), mdy("09-30-16")), the_date)
```

The `within_dates` function is *a lot* like how `within_bounds` is implemented.

You can also achieve this with an anonymous function:
```
these %>%
    assert(function(x){x %within% (mdy("09-01-16") %--% mdy("09-30-16"))}, the_date)
```

Do these help?

**Comment by TonyLadson** [comment]
Thank you, very helpful.  I'm using these approaches already.

**Comment by tonyfischetti** [comment]
I'll put an example of this in the vignette!
