### ISSUE TITLE
Implement assertr::insist on dataframe grouped with dplyr::group_by

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [ropensci/assertr#41]
What about being able to run functions like `within_n_mads()` on a group wise basis, for example:

```
library(dplyr)
library(assertr)

mtcars %>%
  group_by(cyl) %>%
  insist(within_n_mads(2), mpg)
```

Unless I'm very much mistaken, this isn't currently implemented, but would be extremely powerful for testing datasets which are a mix of categorical and continuous variable.

**Comment by ivyleavedtoadflax** [comment]
Although... I suppose you can always do this:

```
library(dplyr)
library(purrr)
library(assertr)

mtcars %>%
  split(.$cyl) %>%
  purrr::map(function(x) insist(x, within_n_mads(2), mpg))
```

**Comment by tonyfischetti** [comment]
Hmm, let me look into what exactly is returned by a `group_by` since that'll inform the approach. I haven't really ever used `group_by` without an immediate `summary` so I'm not sure.

**Comment by tonyfischetti** [comment]
Just looked into it. I'd basically implement it not too differently than your last comment. That looks good enough to me but it you strongly disagree, let me know!

**Comment by ivyleavedtoadflax** [comment]
No, i think you are spot on, in fact that's pretty much what I have implemented here: https://github.com/ukgovdatascience/eesectors/blob/master/R/year_sector_data.R#L131

**Comment by sophof** [comment]
To be honest I have a similar wish. There is a workaround for everything, imo the point of the package is convenience, no? So I may not be the original poster, but I do strongly disagree ;)
The fact that right now the entire dataframe is used by assertr where dplyr is using groups is at the very least not intuitive and a likely source of bugs. But I also think grouped assertions would make the package much more powerful (I tend to use groups a lot).

**Comment by jjchern** [comment]
Here's another workaround before grouped assertions become available:

```R

library(tidyverse)
library(assertr)
packageVersion("assertr")
#> [1] '2.0.2.2'

# Case 1: No FALSEs are found. Return the original tibble.
mtcars %>% 
    nest(-cyl) %>% 
    mutate(data = map(data, ~insist(.x, within_n_mads(4), mpg))) %>% 
    unnest()
#> # A tibble: 32 x 11
#>      cyl   mpg  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  6.00  21.0   160 110    3.90  2.62  16.5  0     1.00  4.00  4.00
#>  2  6.00  21.0   160 110    3.90  2.88  17.0  0     1.00  4.00  4.00
#>  3  6.00  21.4   258 110    3.08  3.22  19.4  1.00  0     3.00  1.00
#>  4  6.00  18.1   225 105    2.76  3.46  20.2  1.00  0     3.00  1.00
#>  5  6.00  19.2   168 123    3.92  3.44  18.3  1.00  0     4.00  4.00
#>  6  6.00  17.8   168 123    3.92  3.44  18.9  1.00  0     4.00  4.00
#>  7  6.00  19.7   145 175    3.62  2.77  15.5  0     1.00  5.00  6.00
#>  8  4.00  22.8   108  93.0  3.85  2.32  18.6  1.00  1.00  4.00  1.00
#>  9  4.00  24.4   147  62.0  3.69  3.19  20.0  1.00  0     4.00  2.00
#> 10  4.00  22.8   141  95.0  3.92  3.15  22.9  1.00  0     4.00  2.00
#> # ... with 22 more rows

# Case 2: At least one row yields FALSE. Terminate the pipeline.
mtcars %>% 
    nest(-cyl) %>% 
    mutate(data = map(data, ~insist(.x, within_n_mads(3), mpg))) %>% 
    unnest()
#> Column 'mpg' violates assertion 'within_n_mads(3)' 2 times
#>   index value
#> 1     6  10.4
#> 2     7  10.4
#> Error in mutate_impl(.data, dots): Evaluation error: assertr stopped execution.
```

Compared to [the "split" approach](https://github.com/ropensci/assertr/issues/41#issuecomment-265467430), the "nest" approach is faster, especially when the assertion is done across many groups.

**Comment by tonyfischetti** [comment]
@ivyleavedtoadflax hi! I just check the code you linked to again (in the `eesectors` package)
Is `raise_issue` the same as `error_warn`? Did you know about it?

**Comment by tonyfischetti** [comment]
Working on this now. Hopefully I can get this included in the new CRAN release

**Comment by tonyfischetti** [comment]
Anyone have any ideas on whether the verbs should call `ungroup` before ending or whether it should be up to the user to put `ungroup` in the pipeline after the assertions?

**Comment by jjchern** [comment]
I guess it might be better to let users decide when to `ungroup`. Consider a series of grouped assertions:

```R
df %>% 
    group(grp) %>% 
    assert(in_set(3, 4), var_a) %>% 
    verify(var_b != 5) %>% 
    ungroup()
```

**Comment by ivyleavedtoadflax** [comment]
Hi @tonyfischetti thanks for the heads-up. I'm not working on that project anymore, but @mammykins or @maxwell8888 might be interested to hear!

**Comment by sophof** [comment]
I would also be for an "ungroup()" called by the user. It would make it clearer what is going on. As far as I know the only function to ungroup automatically is "add_count()" and there it makes some sense. At the very least any function that ungroups automatically should also do the grouping, so that in a sense the group is invisible. However, for assertr I think this isn't really a use case.

**Comment by tonyfischetti** [comment]
I'm having a lot of trouble with the packages in the tidyverse changing things around right now and I'd like to limit usage of these constantly changing new packages/functions. I also unfortunately know a lot of people whose code has been relying on assertr *not* doing grouped assertions. As long as there are workarounds that work, or there is a user (someone in ROpenSci maybe) willing to add this and maintain this functionality when the API changes and the tests invariably fail, I'm gonna close this issue for now
