### ISSUE TITLE
Assertion for duplicates

### ISSUE THREAD

**Issue by rgknight** [ropensci/assertr#42]
Hi thanks for putting together assertr. I am new to using it, sorry if this should be straightforward. 

How would you approach writing a custom predicate for duplicates using assertr? It seems that some basic design choices of assertr make this hard.

The function should:

- Test whether specified vars are **joinly** duplicates
- Tell you something informative on failure (ideal would be the number of unique duplicate values, number of total duplicated rows, and an example set of row numbers with duplicates. Minimum would be the number of unique duplicate values)
- Be extremely fast

My understanding is that this would be hard because `assert` applies the predicate function to each specified variable, and I would want all of the specified variables passed to the predicate function.

The ideal would be something like:
```
df <- data.frame(
    country = c("USA", "USA", "Canada", "Canada"), 
    region = c("Alabama", "Alabama", "Alberta", "Quebec")
)
df %>% assert(no_duplicates, country, region)
#Error: 
#country, region in df has 1 unique duplicated value and 2 duplicated rows (e.g., (1, 2))
```
Or maybe it's just `assert(no_duplicates(country, region))`? 

Thanks.

**Comment by tonyfischetti** [comment]
Good question!
```
> is_uniq <- function(avector) !duplicated(avector)
> attr(is_uniq, "call") <- "is_uniq"
> attr(is_uniq, "assertr_vectorized") <- TRUE
> df %>% assert(is_uniq, country, region)
#Column 'country' violates assertion 'predicate' 2 times
#  index  value
#1     2    USA
#2     4 Canada
#Column 'region' violates assertion 'predicate' 1 time
# index   value
#1     2 Alabama
#Error: assertr stopped execution
```
I'll be adding this function into the package soon but you can use the top three lines of code to do what you'd like in the mean time :)

**Comment by rgknight** [comment]
Thanks! This will definitely be helpful. 

My question was actually a little bit different. I am interested in testing whether country and region are unique together. So the USA-Alabama combination should fail but the Canada-Province validation should pass. 

Does that make sense?

**Comment by tonyfischetti** [comment]
Got it! Sorry, I misunderstood.

```
df <- data.frame(
    country = c("USA", "USA", "Canada", "Canada"), 
    region = c("Alabama", "Alabama", "Alberta", "Quebec")
)

is_uniq <- function(avector) !duplicated(avector)
attr(is_uniq, "call") <- "is_uniq"
attr(is_uniq, "assertr_vectorized") <- TRUE

col_concat <- function(df){
  apply(df, 1, paste0, sep="", collapse="")
}
attr(col_concat, "call") <- "col_concat"

df %>%
  assert_rows(col_concat, is_uniq, country, region)
```

How about this? Does this work?

**Comment by tonyfischetti** [comment]
I hope that's a happy laugh and not a "that solution sucks" laugh because I'm putting this in now

**Comment by tonyfischetti** [comment]
Done ee74656eb80dc8bed4450039bb6c9620b4909ea6
