### ISSUE TITLE
error function that returns data that triggered errors

### ISSUE THREAD

**Issue by RoyalTS** [ropensci/assertr#45]
Would it be possible to have an error function that returns the data that failed at least one test?

**Comment by tonyfischetti** [comment]
Yeah, absolutely! All error functions take `data` as the second argument. For example, this is (at time of writing) `error_stop`...
```
error_stop <- function(errors, data=NULL, warn=FALSE, ...){
  if(!is.null(data) && !is.null(attr(data, "assertr_errors")))
    errors <- append(attr(data, "assertr_errors"), errors)
  lapply(errors, summary)
  if(!warn)
    stop("assertr stopped execution", call.=FALSE)
  warning("assertr encountered errors", call.=FALSE)
  return(data)
}
```

All the assertion verbs give the data frame as the second argument to any error function.

Maybe this will work for you?
```
error_ret_data <- function(errors, data=NULL){
  return(data)
}
```

Does this answer your question? Or was there a more specific need

**Comment by tonyfischetti** [comment]
I'm gonna close this for now. Let me know if this doesn't work for you and I'll reopen it!
