### ISSUE TITLE
feature request: adding attribute information for succeeded assertions

### ISSUE THREAD

**Issue by lorenzwalthert** [ropensci/assertr#48]
I am looking for ways to visualise the result of an assertr chain, i.e. with shiny. Therefore, I need a complete list of succeeded and failed assertions. Setting the option `error_fun` to `error_append` in `chain_end` gives error messages for failed assertions as attributes. I think it would be helpful to also get something similar for successful assertions, so at the end of the chain, I have a complete list of all assertions tested and whether they failed or not. I looked at the source code and it seems the just adding a new success_and_error_function is not sufficient to achieve my goal.

**Comment by tonyfischetti** [comment]
Hmm, this does seem like a worthwhile addition. Any ideas?

**Comment by tonyfischetti** [comment]
I think this is a good idea.
Looking into it, it looks like adding another function that `success_fun` could take called `success_append` would be a good approach

**Comment by tonyfischetti** [comment]
This functionality was added by  @krystian8207 and @Appsilon.
Big thank you to them.
The details should be in the vignette. Let me know if you have any trouble!
