### ISSUE TITLE
Not return the data frame on success?

### ISSUE THREAD

**Issue by ChrisHIV** [ropensci/assertr#52]
Is it possible to have assert() not return the data frame? I tried setting `success_fun = function() {}` but it complains
`Error in success_fun(data) : unused argument (data)`
I want to use assert() to implement a check but do nothing if it passes. Returning the data frame results in it being printed to the screen when I run my code from the command line. Wrapping the check inside `capture.output(assert(...), file='/dev/null')` causes problems when there is an error.

**Comment by tonyfischetti** [comment]
```
mtcars %>% assert(within_bounds(0,10), cyl, success_fun=function(data){invisible(data)})
##
this <- function(data){invisible(data)}
mtcars %>% assert(within_bounds(0,10), cyl, success_fun=this)
##
assert_no_return <- function(...){ assert(..., success_fun=this)}
mtcars %>% assert_no_return(within_bounds(0,10), cyl)
```

Does this work for you?

**Comment by ChrisHIV** [comment]
Yes! Thank you!
