### ISSUE TITLE
Adding print output to stop/warning functions

### ISSUE THREAD

**Issue by dustindall** [ropensci/assertr#54]
I have a use for this package where I'm iterating over many data frames using map and verifying their inputs. I want to be able to identify which ones are a success and which ones have an error with the error information included.

In the current setup of the package, the error information is not captured. Below is a reproducible example.

```
library(tidyverse) 
library(assertr)

safe_assert <- safely(assert)
current <- map(seq(20, 40, 10), ~{
  safe_assert(mtcars, within_bounds(0, .x), mpg, error_fun = error_report)})

current
```

[[1]]
[[1]]$result
NULL

[[1]]$error
<simpleError: assertr stopped execution>

[[2]]
[[2]]$result
NULL

[[2]]$error
<simpleError: assertr stopped execution>

[[3]]
[[3]]$result
                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4

I think it would be beneficial to include the print information in the `stop` and `warning` functions of the `error_report` function (see below). Have you considered this?

```
error_report <- function(errors, data=NULL, warn=FALSE, ...){
  if(!is.null(data) && !is.null(attr(data, "assertr_errors")))
    errors <- append(attr(data, "assertr_errors"), errors)
  num.of.errors <- length(errors)
  head <- paste0(sprintf("There %s %d error%s:\n",
                         if (num.of.errors==1) "is" else "are",
                         num.of.errors,
                         if (num.of.errors==1) "" else "s"))
  body <- sapply(errors, function(x) paste0("\n- ", x))
  if(!warn)
    stop(paste0("assertr stopped execution", "\n\n", head, body, "\n"), call.=FALSE)
  warning(paste0("assertr encountered errors", "\n\n", head, body, "\n"), call.=FALSE)
  return(data)
}
```

Rerunning the same example with the changes to `error_report` the new output is below.

```
library(tidyverse) 
library(assertr)

# with change to error_report function()
safe_assert <- safely(assert)
current <- map(seq(20, 40, 10), ~{
  safe_assert(mtcars, within_bounds(0, .x), mpg, error_fun = error_report)})

current
```

[[1]]
[[1]]$result
NULL

[[1]]$error
<simpleError: assertr stopped execution

There is 1 error:

- Error in "within_bounds(0, .x)": Column 'mpg' violates assertion 'within_bounds(0, .x)' 14 times

[[2]]
[[2]]$result
NULL

[[2]]$error
<simpleError: assertr stopped execution

There is 1 error:

- Error in "within_bounds(0, .x)": Column 'mpg' violates assertion 'within_bounds(0, .x)' 4 times

[[3]]
[[3]]$result
                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4

If you are open to this, let me know and I can make a pull request. And if you don't want to make the change to the default settings, a solution could be having a global package option to include or not include in the `stop` and `warning` functions.

Thanks. This is a great package!

**Comment by tonyfischetti** [comment]
I think this is a fantastic idea. If you could make the pull request that would be great
And if you can make tests that would be super super cool :)
Btw, what is `safe_assert`?

**Comment by tonyfischetti** [comment]
Hi! If you're still open to making a pull request for this, let me know :)

**Comment by dustindall** [comment]
Sorry for the delay. Yes, i'm still interested in making the pull request. It might be another week or two before i get around to it though.

**Comment by tonyfischetti** [comment]
That's totally cool :) I was just checking. No rush!

**Comment by tonyfischetti** [comment]
I'm trying to close issues to reduce the amount of stuff weighing over me (the number of unresolved issues on my open source projects). Still no rush on the pull request but I'm gonna close this issue for now
