### ISSUE TITLE
Feature request: support for .data pronoun

### ISSUE THREAD

**Issue by karldw** [ropensci/assertr#56]
Thanks for the great package!

I'm wondering if you'd consider adding support for the `.data` and `.env` pronouns from the tidyverse's new tidyeval framework. (`.data` says "look in the dataframe for the column" while `.env` says something like "look in the environment for the value")

See the [dplyr programming vignette](http://dplyr.tidyverse.org/articles/programming.html) has some background.)  I think the [`rlang::eval_tidy`](http://rlang.tidyverse.org/reference/eval_tidy.html) function will be key here.

Here's a demo:
```r

library(rlang)
library(assertr)

mtcars %>% verify(mpg > 30)  # verify works!
#> verification [mpg > 30] failed! (28 failures)

mgp <- 40
mtcars %>% verify(mgp > 30)  # fat fingers :(
# No error because mgp exists elsewhere

# I'd like to write:
mtcars %>% verify(.data$mpg > 30)
# and 
mtcars %>% verify(.data$mpg > .env$mgp)


# How it works in dplyr:
mtcars %>% dplyr::mutate(x = mgp)  # no error, but mgp always 40

# but if we're careful, we get an error
mtcars %>% dplyr::mutate(x = .data$mgp)
#> Error in mutate_impl(.data, dots) : 
#>  Evaluation error: Column `mgp`: not found in data.


```

**Comment by karldw** [comment]
Hmm, it seems that `.env` might not be helpful because of the way `%>%` works.  See  https://github.com/tidyverse/rlang/pull/339 for details.  
I think `.data` might still be useful.

**Comment by tonyfischetti** [comment]
Haha, I'll have to read the vignette you posted.
I'll check back in when I've read it

Thanks for the suggestion :)

**Comment by tonyfischetti** [comment]
Hi!
I'd definitely consider adding this. I see you're a contributor to `rlang`, would you like to submit a pull request? I feel like I don't understand rlang nearly as well as you.

**Comment by karldw** [comment]
Sure! It will be a bit before I'm able to write the PR, but it's on my list.

**Comment by tonyfischetti** [comment]
Great! Thank you very much :)
