### ISSUE TITLE
Add predicate for percentage of records with that value...

### ISSUE THREAD

**Issue by tonyfischetti** [ropensci/assertr#61]
This would _help_ identify misspecied categorical variables. If, for example, in `iris` a few `versicolor`s were `versecolor`, the percentage of records with that value would be low.

I haven't thought this through yet. Can I use with `within_bounds`? Or is it it's own complete function?

**Comment by tonyfischetti** [comment]
Nah

**Comment by JanaJarecki** [comment]
sad :D anybody implemented this?

**Comment by tonyfischetti** [comment]
Now that I know there's an interest in this, I'll re-open the issue and think through a solution
