### ISSUE TITLE
Add custom error message

### ISSUE THREAD

**Issue by RKonstantinR** [ropensci/assertr#70]
Thank you for this great package! 

Can you add one more argument like "msg" argument in assetr_that functions  (assertthat package) to assert and verify functions?

**Comment by tonyfischetti** [comment]
You can do this by overriding the error function!
err_msg <- function(msg) stop(msg, call.=FALSE)
d <- data.frame(a=1:3, b=4:6)
d %>% verify(has_all_names("a", "b", "c"), error_fun=err_msg("NAH SON"))
