### ISSUE TITLE
predicate function request: not_in_set

### ISSUE THREAD

**Issue by marceltoebes** [ropensci/assertr#84]
Hi,
(I like this library and I would like to contribute but don't know the conventions of how to do that)
For my use case I had to create the "not_in_set" predicate function. I guess more people could use that one in the data analysis pipeline and it would be nice to have it in the library. It is simply the inverse of the in_set predicate function.

not_in_set <- function (..., allow.na = TRUE) 
{
  the_call <- deparse(sys.call())
  set <- c(...)
  if (!length(set)) 
    stop("can not test for membership in empty set")
  fun <- function(x) {
    if (is.null(x)) 
      stop("nothing to check set membership to")
    raw_result <- **!(x %in% set)**
    if (allow.na) {
      these_are_NAs <- is.na(x)
      raw_result[these_are_NAs] <- TRUE
    }
    return(raw_result)
  }
  attr(fun, "assertr_vectorized") <- TRUE
  attr(fun, "call") <- the_call
  return(fun)
}

**Comment by tonyfischetti** [comment]
Thanks for the suggestion and sorry for the delay!
I just pushed a commit such that `in_set` has an `inverse` flag that tests if the arguments are *not* in the set.
I'm going to try to address some other things and then I'll upload to CRAN. In the meantime, feel free to install it from github with `devtools::install_github("ropensci/assertr")`
