### ISSUE TITLE
assert does not always report errors

### ISSUE THREAD

**Issue by richardjtelford** [ropensci/assertr#85]
I've been having problems getting `assert` to print errors in a package I'm writing. Some calls to `assert` work properly and some don't.

Here is a reproducible example which gives the same symptoms. 

```
#works  
assert(data.frame(x = c("a", "b")), in_set("b"), x)
```
> Column 'x' violates assertion 'in_set("b")' 1 time
>     verb redux_fn   predicate column index value
> 1 assert       NA in_set("b")      x     1     a
> 
> Error: assertr stopped execution

```
#doesn't work  
assert(data.frame(x = "a"), in_set("b"), x)
```

> Error: assertr stopped execution

I think the problem is because in the latter example 

```
 log.mat <- sapply(names(sub.frame), function(column) {
    this.vector <- sub.frame[[column]]
    return(apply.predicate.to.vector(this.vector, predicate))
  })
```
returns a vector rather than a matrix so `colnames` in 

```
 errors <- lapply(colnames(log.mat),
```
returns NULL and the `lapply` doesn't run.

**Comment by tonyfischetti** [comment]
Sorry for the delay, checking this out now

**Comment by tonyfischetti** [comment]
Just fixed this issue! Thanks for noticing it :)
I'm going to try to address some other things and then I'll upload to CRAN. In the meantime, feel free to install it from github with `devtools::install_github("ropensci/assertr")`

**Comment by richardjtelford** [comment]
Brilliant. `assert` now reports errors properly in my package.

**Comment by tonyfischetti** [comment]
Glad to here it. Thanks again for bringing the issue to my attention
