### ISSUE TITLE
Passing custom arguments to error_fun

### ISSUE THREAD

**Issue by ngupta23** [ropensci/assertr#90]
I want to pass custom arguments to error_fun, but am unable to do so. Is this capability supported?

I am getting the following error message when passing custom arguments.

Error in assertr::verify(., has_all_names("mpg2"), error_fun = error_udf_3, : unused arguments (calling_fun = "main", message = "columns name does not match")

[assertr_custom_args.zip](https://github.com/ropensci/assertr/files/3643291/assertr_custom_args.zip)

My use case is as follows: I have created several classes and there are many levels of inheritance. I would like to use a common error function which has arguments called "calling_fun" which indicates which function the error is coming from and "message" which has a user defined string message. This way, I can reuse a common error function rather than defining multiple custom error functions.

Thanks!

**Comment by tonyfischetti** [comment]
If I understand this correctly, I think this can this be solved with a closure.
So you pass the arguments into a error function builder and *that*function  returns a function that can be used as the error function.
Kind of like how `within_bounds` doesn't actually check bounds but builds a function that checks it after closing over the provided arguments
