### ISSUE TITLE
assertr::assert problem on grouped data

### ISSUE THREAD

**Issue by richardjtelford** [ropensci/assertr#91]
Here is a minimal example
```
library(tidyverse)
library(assertr)
iris %>% 
  group_by(Species) %>% 
  verify(Petal.Length > 0) %>% #works fine
  assert(within_bounds(0, 100), Sepal.Length) #fails
```
>Adding missing grouping variables: `Species`
Error in predicate(a.column) : bounds must only be checked on numerics

The problem is that the line of code in assert

```
sub.frame <- dplyr::select(data, !!!(keeper.vars))
```
will try to drop the grouping variables, but dplyr will add them back again.

One solution would be to change this line to 

```
sub.frame <- dplyr::select(dplyr::ungroup(data), !!!(keeper.vars))
```

An alternative would be to use `dplyr::is.grouped_df`and give a warning advising to ungroup data first.

**Comment by tonyfischetti** [comment]
I think this would be worthwhile to pursue.
I'd be happy to accept a pull request :)
