### ISSUE TITLE
assert has error for single-row data frames and multiple columns

### ISSUE THREAD

**Issue by jayqi** [ropensci/assertr#94]
`assert` errors when making an assertion on multiple columns for a single-row data frame. 

My guess is that that the issue involves the internals somewhere incorrectly treating the row as a vector, rather than as multiple length-one vectors. `assert` works fine with one-row-one-column, or multiple-rows-multiple-columns

Reproducible example, asserting on two columns with a single-row data frame:

``` r
library(assertr)
library(magrittr)
head(mtcars, 1) %>% assert(not_na, am, vs)
#> Error in dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent
```

``` r
packageVersion("assertr")
#> [1] '2.7'
```

---

Note that this error does not occur when asserting about only a single column for a single-row data frame:

``` r
library(assertr)
library(magrittr)
head(mtcars, 1) %>% assert(not_na, am)
#>           mpg cyl disp  hp drat   wt  qsec vs am gear carb
#> Mazda RX4  21   6  160 110  3.9 2.62 16.46  0  1    4    4
```

or asserting about multiple columns with multiple-row data frames:

``` r
library(assertr)
library(magrittr)
head(mtcars, 2) %>% assert(not_na, am, vs)
#>               mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4      21   6  160 110  3.9 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag  21   6  160 110  3.9 2.875 17.02  0  1    4    4
```

<sup>Created on 2020-03-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tonyfischetti** [comment]
Sorry for the delay.
I can't replicate this bug on version 2.8. Can you try that?
Should be on CRAN

**Comment by tonyfischetti** [comment]
@mariadrywien I'm working on this now. Should bew done by the end of the day

**Comment by tonyfischetti** [comment]
@mariadrywien Just fixed it. It's in master now. I'm submitting to CRAN now

**Comment by mariadrywien** [comment]
@tonyfischetti Thanks a lot! Works fine now 🙂

**Comment by jakubnowicki** [comment]
Hi @tonyfischetti 
Unfortunately, the issue is still present in the case when you use `assert` with multiple columns. Please check this example (based on the previous one):

```r
library(assertr)
library(magrittr)
data("mtcars")

data_multirow_with_NA <- mtcars
data_multirow_with_NA[1,1] <- NA
data_single_row_with_NA <- head(data_multirow_with_NA, n = 1)

# single-row data frame with NA
data_single_row_with_NA %>% assert(not_na, mpg, cyl)

#>Error: assertr stopped execution
```
