### ISSUE TITLE
CRAN version different from master

### ISSUE THREAD

**Issue by krystian8207** [ropensci/assertr#96]
Hi @tonyfischetti 

I realized the new version of assertr was released (with 2.7 version).
Unfortunately, it is missing the bigger changes from master branch I pushed some time ago (2.6.9000 version).

As a result CRAN version seems to have all the changes from master but is not.
Do you plan to release it soon?

**Comment by tonyfischetti** [comment]
Working on this as we speak

**Comment by tonyfischetti** [comment]
It looks like the new version fails some tests. I have to resolve them before I submit them

**Comment by tonyfischetti** [comment]
That's weird. I see the CI tests passed but the tests are failing on my computer. I'll try it on a vanilla version of R

**Comment by tonyfischetti** [comment]
The missing piece was was the pull request #104 which fixed
3 failures and 103 warnings from the tip of master

I bumped the version number and submitted it to CRAN
Once accepted, I'll close this issue and commit the latest with the
version bump

Thank you for your patience!

**Comment by tonyfischetti** [comment]
assertr 2.8 just hit cran!
