### ISSUE TITLE
Feature Request: Additional Name Verifications

### ISSUE THREAD

**Issue by billdenney** [ropensci/assertr#97]
Thank you for the package!

While in many cases having at least the expected names (via `has_all_names()`) is desired, there are also cases, where having only a certain set of names or having names in an exact order is needed.

Would you consider a PR that implemented one more name checking function (or maybe two functions to cover the two scenarios):

`has_only_names(..., exact=FALSE)` Where it would require that all the names were in the parent frame environment, and no other names were present.  And, if `exact=TRUE`, then the order must match, too.

**Comment by tonyfischetti** [comment]
That would be excellent! I would definitely accept that pull request!
